param(
    [switch]$RemoveBeforeInstall,
    [switch]$Destroy,
    [switch]$UseTfVarsFile
)

# Stop script on any error
$ErrorActionPreference = "Stop"
$ProgressPreference = "SilentlyContinue"

function main() {

    try {
        # (Start) Capture duration metrics
        $BuildTime = [Diagnostics.Stopwatch]::StartNew()

        [Environment]::SetEnvironmentVariable("ADAL_PYTHON_SSL_NO_VERIFY", "1", "Process")
        [Environment]::SetEnvironmentVariable("AZURE_CLI_DISABLE_CONNECTION_VERIFICATION", "1", "Process")


        if (-not($UseTfVarsFile)) {
            az login --service-principal -u "$($Env:client_id)" -p "$($Env:client_secret)" --tenant "$($Env:tenant_id)"
            if ($LASTEXITCODE -ne 0) { throw "Failure logging in to Azure"}
            az account get-access-token
        }
        #return

        # Create tfvars file
        if (-not($UseTfVarsFile)) {
            if (Test-Path .\terraform.tfvars) { Remove-Item -Path .\terraform.tfvars -Force | Out-Null }
            $terraformvars = 
@" 
                subscription_id = "$($Env:subscription_id)"
                client_id = "$($Env:client_id)"
                client_secret = "$($Env:client_secret)"
                tenant_id = "$($Env:tenant_id)"#
"@ 
            $terraformvars | Out-File -FilePath .\terraform.tfvars -Encoding ASCII -Force
        }
        else {
            Write-Warning "Using TfVars File"
        }

        # init
        if (-not(Test-Path "./terraform")) {
            terraform init
            if ($LASTEXITCODE -ne 0) { throw "Failure initialising terraform"}
        }

        if ($Destroy) {
            terraform destroy -auto-approve;
            return
        }

        
        # Used to download and update modules mentioned in the root module
        terraform get;

        # Used to validate the syntax of the terraform files
        terraform validate
        if ($LASTEXITCODE -ne 0) { throw "Failure validating terraform files"}


        # Used to create an execution plan
        terraform plan
        if ($LASTEXITCODE -ne 0) { throw "Failure executing terraform plan"}

        # Used to apply the changes required to reach the desired state of the configuration, or the pre-determined set of actions generated by a terraform plan execution plan
        terraform apply -auto-approve;
        if ($LASTEXITCODE -ne 0) { throw "Failure executing terraform apply"}
        
        # Display execution duration
        $BuildTime.Stop()
        $TimeOutput = $BuildTime.Elapsed
        Write-Host "Total build time: [$($TimeOutput.Minutes)m $($TimeOutput.Seconds)s]"
    }
    catch {
        Write-Error $_.Exception.Message
        throw
    }
    finally {
        # Clean up
        if (-not($UseTfVarsFile)) {
            if (Test-Path .\terraform.tfvars) {
                Remove-Item -Path .\terraform.tfvars -Force | Out-Null
            }
        }
    }
} 

main